$(()=>{
	$(".h5-1").click(()=>{
		$(".h5-1").toggleClass("active-h");
		$(".ul-1").slideToggle();
		$(".ul-2").slideUp();
		$(".ul-3").slideUp();
		$(".ul-4").slideUp();
		$(".form-1").slideUp();
		$(".h5-2").removeClass("active-h");
		$(".h5-3").removeClass("active-h");
		$(".h5-4").removeClass("active-h");
		$(".h5-5").removeClass("active-h");

	});
	$(".h5-2").click(()=>{
		$(".h5-2").toggleClass("active-h");
		$(".ul-2").slideToggle();
		$(".ul-1").slideUp();
		$(".ul-3").slideUp();
		$(".ul-4").slideUp();
		$(".form-1").slideUp();
		$(".h5-1").removeClass("active-h");
		$(".h5-3").removeClass("active-h");
		$(".h5-4").removeClass("active-h");
		$(".h5-5").removeClass("active-h");
	});
	$(".h5-3").click(()=>{
		$(".h5-3").toggleClass("active-h");
		$(".ul-3").slideToggle();
		$(".ul-2").slideUp();
		$(".ul-1").slideUp();
		$(".ul-4").slideUp();
		$(".form-1").slideUp();
		$(".h5-2").removeClass("active-h");
		$(".h5-1").removeClass("active-h");
		$(".h5-4").removeClass("active-h");
		$(".h5-5").removeClass("active-h");
	});
	$(".h5-4").click(()=>{
		$(".h5-4").toggleClass("active-h");
		$(".ul-4").slideToggle();
		$(".ul-2").slideUp();
		$(".ul-3").slideUp();
		$(".ul-1").slideUp();
		$(".form-1").slideUp();
		$(".h5-2").removeClass("active-h");
		$(".h5-3").removeClass("active-h");
		$(".h5-1").removeClass("active-h");
		$(".h5-5").removeClass("active-h");
	});
	$(".h5-5").click(()=>{
		$(".h5-5").toggleClass("active-h");
		$(".form-1").slideToggle();
		$(".ul-1").slideUp();
		$(".ul-2").slideUp();
		$(".ul-3").slideUp();
		$(".ul-4").slideUp();
		$(".h5-2").removeClass("active-h");
		$(".h5-3").removeClass("active-h");
		$(".h5-4").removeClass("active-h");
		$(".h5-1").removeClass("active-h");
	});
});